HEADERS += /usr/local/include

LIBS += /usr/local/lib/libcrypto.so
LIBS += /usr/local/lib/libssl.so


SOURCES += main.cpp


aes_test : 
	g++ -o aes_test $(SOURCES) $(HEADERS) $(LIBS)


.PHONY : clean


clean :
	rm -f aes_test 

























